name: Create release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: npm build
      - name: version
        run: echo "::set-output name=version::$(./bin/santander --version)"
        id: version
      - name: build artifacts
        run: make build-linux
    name: create_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

  - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/santander.linux-amd64.tar.gz
          asset_name: santander.linux-amd64.tar.gz
          asset_content_type: application/gzip
     #- name: upload darwin artifact
     #  uses: actions/upload-release-asset@v1
     #  env:
     #    GITHUB_TOKEN: ${{ github.token }}
     #  with:
     #    upload_url: ${{ steps.create_release.outputs.upload_url }}
     #    asset_path: ./bin/santander.darwin-amd64.tar.gz
     #    asset_name: santander.darwin-amd64.tar.gz
     #    asset_content_type: application/gzip
     # - name: upload windows artifact
     #   uses: actions/upload-release-asset@v1
     #   env:
     #     GITHUB_TOKEN: ${{ github.token }}
     #   with:
     #     upload_url: ${{ steps.create_release.outputs.upload_url }}
     #     asset_path: ./bin/santander.windows-amd64.zip
     #     asset_name: santander.windows-amd64.zip
     #     asset_content_type: application/zip