name: Santander - Teste

on:
  push:
    branches: main
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write
  actions: read

jobs:

  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install

    - name: Checkout repository
      uses: actions/checkout@v2
          
    - name: Login Azure
      uses: azure/docker-login@v1
      with:
        version: v0.7.0
        login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}
    - name: Build and Push image to ACR
      run: |
        docker build -t ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/santander:${{ github.sha }} .
        docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/santander:${{ github.sha }}

  release:
    needs: build
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: tsc --build
        
      - name: version
        run: echo "::set-output name=version::$(./bin/santander --version)"
        id: version

      - name: build artifacts
        run: tsc --build

      - name: create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.run_number }}
          tag_name: ${{ github.run_number }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
        #  asset_path: ./bin/santander.linux-amd64.tar.gz
          asset_name: santander.linux-amd64.tar.gz
          asset_content_type: application/gzip

  deploy-aks-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Access Cluster AKS
        id: set-context
        uses: Azure/aks-set-context@v3
        with:          
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          admin: true
          use-kubelogin: false

      - name: Deploy
        uses: Azure/k8s-deploy@v4
        with:
          namespace: frontend
          actions: deploy
          manifests: |
            manifest/santander-deploy.yaml
          images: |
            ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/santander:${{ github.sha }}