name: EAF FrontEnd Stage
on:
  push:
   branches: [ main ]

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node 17.x
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'
    
    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: |
        ./build.sh

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v2
      with:
        args: "dist/bin/ dist/shell/compiled.sh"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

 # build-push:
 #   needs: unit-test
 #   runs-on: ubuntu-latest
 #   steps:
 #     - name: Checkout repository
 #       uses: actions/checkout@v2
 #           
 #     - name: Login Azure
 #       uses: azure/docker-login@v1
 #       with:
 #         version: v0.7.0
 #         login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
 #         username: ${{ secrets.AZURE_ACR_USERNAME }}
 #         password: ${{ secrets.AZURE_ACR_PASSWORD }}
#
 #     - name: Build and Push image to ACR
 #       run: |
 #         docker build -t ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/santander:${{ github.sha }} .
 #         docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/santander:${{ github.sha }}                 
#
 # deploy-aks-stage:
 #   needs: build-push-to-acr
 #   runs-on: ubuntu-latest
 #   steps:
 #     - name: Checkout repository
 #       uses: actions/checkout@v2
#
 #     - name: Login Azure
 #       uses: azure/login@v1
 #       with:
 #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
 #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
 #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 #         #creds: ${{ secrets.AZURE_CREDENTIALS }}
#
 #     - name: Access Cluster AKS
 #       id: set-context
 #       uses: Azure/aks-set-context@v3
 #       with:          
 #         resource-group: ${{ secrets.RESOURCE_GROUP_STG }}
 #         cluster-name: ${{ secrets.CLUSTER_NAME_STG }}
 #         admin: true
 #         use-kubelogin: false
#
 #     - name: Deploy
 #       uses: Azure/k8s-deploy@v4
 #       with:
 #         namespace: frontend
 #         actions: deploy
 #         manifests: |
 #           manifests/santander-deployment.yaml
 #         images: |
 #           ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/santander:${{ github.sha }}    
#